# Generated by Django 6.0.3 on 2026-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marigoldApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
