# Generated by Django 6.0.3 on 2026-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marigoldApp", "0002_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
