# Generated by Django 6.0.3 on 2026-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marigoldApp", "0003_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping & Delivery"),
                            ("products", "Products & Ingredients"),
                            ("care", "Candle Care Tips"),
                            ("orders", "Orders & Custom Work"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
    ]
