# Generated by Django 6.0.3 on 2026-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marigoldApp", "0004_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("custom", "Custom / Bespoke Order"),
                            ("wholesale", "Wholesale Enquiry"),
                            ("order", "Order Question"),
                            ("general", "General Hello"),
                            ("other", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["-category", "order"]},
        ),
    ]
