# Generated by Django 6.0.3 on 2026-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marigoldApp", "0005_contactmessage_alter_faq_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
