"""
Django settings for marigoldsite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['marigold-8xdf.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary_storage",
    "cloudinary", 
    "marigoldApp",
    "sendgrid_backend",
    "maintenance_mode",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "marigoldsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",    # {{ MEDIA_URL }}
                "django.template.context_processors.static",   # {{ STATIC_URL }}
                "marigoldApp.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "marigoldsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ── Database ──────────────────────────────────────────────────
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
    default=os.getenv('DATABASE_URL'),
    conn_max_age=600,
    ssl_require=True,  
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#── Cloudinary ────────────────────────────────────────────────
import cloudinary

cloudinary.config(
    cloudinary_url=os.getenv('CLOUDINARY_URL')
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY':    os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Email configuration
# Email configuration for SendGrid

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'nwankwoifeanyi21@outlook.com')



MAINTENANCE_MODE = False
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True   
MAINTENANCE_MODE_IGNORE_SUPERUSER = True   
MAINTENANCE_MODE_TEMPLATE = '503.html'   


JAZZMIN_SETTINGS = {
    # ── Branding ──────────────────────────────────────────────
    "site_title": "Marigold Admin",
    "site_header": "Marigold & Co.",
    "site_brand":  "Marigold & Co.",
    "site_logo":   "img/logo.png",
    "login_logo": "img/logo.png",
    "welcome_sign": f"Welcome back, {os.getenv('ADMIN_NAME', 'Admin')}",
    "site_logo_classes": "img-fluid",
    "copyright": "Marigold & Co. — Made with 🤍 in Austin, TX",

    # ── Top navigation ────────────────────────────────────────
    "topmenu_links": [
        {"name": "Dashboard",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View The Site",  "url": "/", "new_window": True},
        {"name": "Messages",   "url": "/admin/marigoldApp/contactmessage/"},
        {'app': 'marigoldApp'},
         ], 

    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True, "icon": "fas fa-globe"},
        {"name": "Support",   "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True, "icon": "fas fa-life-ring"},

        ],
    # ── Sidebar ───────────────────────────────────────────────
    "show_sidebar":        True,
    "navigation_expanded": True,

    # ── Icons ─────────────────────────────────────────────────
    "icons": {
        "marigoldApp":                "fas fa-seedling",
        "marigoldApp.Product":        "fas fa-box-open",
        "marigoldApp.Review":         "fas fa-star",
        "marigoldApp.FAQ":            "fas fa-question-circle",
        "marigoldApp.ContactMessage": "fas fa-envelope",
        "auth.User":                  "fas fa-user",
        "auth.Group":                 "fas fa-users",
    },
    "default_icon_parents":  "fas fa-folder",
    "default_icon_children": "fas fa-circle",

     # ── Layout ────────────────────────────────────────────────
    "custom_css": 'css/admin_custom.css',
    "custom_js": "js/admin_custom.js",
    "use_google_fonts_cdn":    True,
    "show_ui_builder":         False,

}
JAZZMIN_UI_TWEAKS = {
    "theme": "sandstone",
    "dark_mode_theme": None,        
    "navbar_fixed":    True,
    "sidebar_fixed":   True,
    "sidebar": "sidebar-light-primary",
}


# ── Security ──────────────────────────────────────────────────
SECURE_SSL_REDIRECT          = not DEBUG  # redirect HTTP to HTTPS in production
SECURE_HSTS_SECONDS          = 31536000   # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD          = True
SESSION_COOKIE_SECURE        = not DEBUG  # HTTPS-only session cookie
CSRF_COOKIE_SECURE           = not DEBUG  # HTTPS-only CSRF cookie
SECURE_BROWSER_XSS_FILTER    = True
SECURE_CONTENT_TYPE_NOSNIFF  = True
X_FRAME_OPTIONS              = 'DENY'